# Basic workflow
name: build

# Controls when the action will run
# Workflow begins with push or PR events
# Focuses on the master branch only
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: 
  contents: write

# Create one single job
# This job performs all necessary checks
jobs:
  build:
    # Use the latest version of Ubuntu
    runs-on: ubuntu-latest
    # Define the workflow steps
    steps:
        # Run GatorGrader: see config/gatorgrade.yml
        - name: Checkout repository
          uses: actions/checkout@v3
          with: 
            fetch-depth: '0'
        - name: Run GatorGrader with GatorGrade
          if: always()
          run:  |
            pip install gatorgrade
            gatorgrade --config config/gatorgrade.yml
        - name: If pass, note that pass is preliminary
        #if last check passed, then this will run
          if: ${{ job.status == 'success' }}
          run:  |
            echo "This is a preliminary pass. Professor will evaluate final results."
